### ISSUE TITLE
Configure mediaflux to use the CAS header we configure

### ISSUE THREAD

**Issue by bess** [pulibrary/tiger-data-app#836] opened 2024-07-15 16:35 UTC
## Acceptance criteria

- [ ] Configure mediaflux so that it looks for the http header we send indicating whether the user is CAS authenticated

**Comment by kelynch** [comment] 2024-07-29 18:02
Arcitecta work being tracked here - https://support.arcitecta.com/hc/en-us/requests/6652

**Comment by kelynch** [comment] 2024-08-06 15:33
Duplicate ofr #863, closing

**Closed by kelynch** 2024-08-06 15:33 UTC
